### ISSUE TITLE
Prices incorrect for 1000+ ships

### ISSUE THREAD

**Issue by evilspyre** [dolkensp/HangarXPLOR#1]
Hi,  Love the work you have done with it, but just wanted to report an issue.  With the current version any package over 1000 dollars only shows as the first digit when adding the price in the left hand pricing part of the page.  For example the Armada pack shows as 2 dollars and the Hull-a-palooza pack shows as 1 dollar.  It appears to only be picking up the digit before the comma not the whole value.

**Comment by dolkensp** [comment]
Thanks! Will fix shortly
