### ISSUE TITLE
Firefox 108.0.2 Plugin doesent load anymore

### ISSUE THREAD

**Issue by Einherjar-FTC** [dolkensp/HangarXPLOR#107]
1. Did clear plugin cache
2. did clear normal cache

![grafik](https://user-images.githubusercontent.com/12670786/212426171-1f7db2c9-2f0d-4c19-a5ae-67f93e9e2d1d.png)

**Comment by Maxence-BUNEL** [comment]
Hello,

Absolutely true : Used it yesterday morning with no issue (26-27 hours from now), and is now hanging with a js error since yesterday afternoon. Tried on Firefox, Chrome and Opera. Same issue reported by other players i play with.

Regards.

**Comment by TDPMojo** [comment]
same here it does not load

**Comment by peter-dolkens** [comment]
Thanks all - it looks like CIG/Turbulent have broken something.

Once you modify your hangar - all your pledges lose their names (even with the plugin disabled)

I'm reaching out to them to let them know

<img width="894" alt="image" src="https://user-images.githubusercontent.com/469666/212577419-87f391ea-81eb-44d7-9a26-1ba6bc434ea6.png">

**Comment by peter-dolkens** [comment]
CIG are aware, and will likely take a look this week.

I'll see if there's anything I can do to correct it for HangarXPLOR users on my end tomorrow evening too.

**Comment by peter-dolkens** [comment]
Just pushed an update for this, but it requires Firefox 109 due to the new v3 manifest being forced by Google now (as all browsers currently share the same codebase)

It's being pushed today, so you may need to wait for it to become available:

https://whattrainisitnow.com/release/?version=109
