### ISSUE TITLE
Does not load fully on firefox 108.0.2

### ISSUE THREAD

**Issue by TDPMojo** [dolkensp/HangarXPLOR#108]
I look at my hangar and it does not load like it use to.
![Screenshot 2023-01-14 at 07-19-52 My Hangar - Roberts Space Industries Follow the development of Star Citizen and Squadron 42](https://user-images.githubusercontent.com/84671464/212471397-b79acb8a-12b4-447d-9515-44f98dec9f2d.png)

**Comment by Stargate476** [comment]
same does not load on chrome

**Comment by SeniorOp** [comment]
This is widespread. I'm in an org Discord with about 6-8 people active -- and all of them tested it yesterday, some with multiple browsers. It fails hard, as described, in Chrome, Brave, Edge, Vivaldi ...

I'm the only one using Firefox, and it has not broken for me yet. A pattern may be that the extension breaks if anything is melted from or added to the hangar. I have not done either recently, and it continues to work for me.

**Comment by peter-dolkens** [comment]
Will take a look. Sounds like one of the API calls has been changed

**Comment by peter-dolkens** [comment]
Thanks all - it looks like CIG/Turbulent have broken something.

Once you modify your hangar - all your pledges lose their names (even with the plugin disabled)

I'm reaching out to them to let them know

<img width="894" alt="image" src="https://user-images.githubusercontent.com/469666/212577419-87f391ea-81eb-44d7-9a26-1ba6bc434ea6.png">

**Comment by peter-dolkens** [comment]
CIG are aware, and will likely take a look this week.

I'll see if there's anything I can do to correct it for HangarXPLOR users on my end tomorrow evening too.

**Comment by peter-dolkens** [comment]
Just pushed an update for this, but it requires Firefox 109 due to the new v3 manifest being forced by Google now (as all browsers currently share the same codebase)

It's being pushed today, so you may need to wait for it to become available:

https://whattrainisitnow.com/release/?version=109
