### ISSUE TITLE
Ships gifted by CIG do not show

### ISSUE THREAD

**Issue by NlGHTLORD** [dolkensp/HangarXPLOR#109]
Won a Vulture by CIG.  They placed it in my hangar.  It shows until Xplor plugs in and then it disappears.  Let me know if you need anything.  Thanks!

**Comment by peter-dolkens** [comment]
Thanks Nightlord.

If you click the HangarXPLOR icon, and click "clear cache", it should
resolve the issue I believe.

CIG cheat a bit sometimes when they gift ships, which makes it hard for me
to detect that the cache should expire.

Can you try the above and get back to me?

**Comment by NlGHTLORD** [comment]
You are 100% correct as always sir.  That solved it. Cheers Mate!!
