### ISSUE TITLE
Referral bonuses not shown

### ISSUE THREAD

**Issue by VioletD0ll** [dolkensp/HangarXPLOR#125]
Hello, I've noticed that when this plugin on Chrome is loaded, the Dragonfly I got as a referral bonus doesn't appear in a hangar. I used another browser without plugin to make sure and it appeared in this one, it also appears when I open hangar before the plugin is loaded

**Comment by peter-dolkens** [comment]
Can you click the plugon icon and then clear cachePeter DolkensOn 12 Apr 2024, at 01:47, VioletD0ll ***@***.***> wrote:﻿
Hello, I've noticed that when this plugin on Chrome is loaded, the Dragonfly I got as a referral bonus doesn't appear in a hangar. I used another browser without plugin to make sure and it appeared in this one, it also appears when I open hangar before the plugin is loaded

**Comment by VioletD0ll** [comment]
I tried that and it now work perfectly, thank you
