### ISSUE TITLE
HoloXPLOR - Error while processing XML file

### ISSUE THREAD

**Issue by SilverlightPony** [dolkensp/HangarXPLOR#2]
System doesn't give any details or error codes, it just says:

> ## Error
> 
> An error occurred while processing your request.

I've tried to upload my XML file about twenty times, using both Firefox (well, Waterfox) and Chrome.  The only time I didn't get this error was the second attempt on Firefox (after which I didn't seem to be able to actually change the loadout on my Gladius, but that's a separate issue).

**Comment by dolkensp** [comment]
Hey - are you able to PM me the name of your XML file - and I can take a look.

Looking at the time - you may have tried right as I was pushing the updates for 2.1.2, so it may actually be working now.

**Comment by dolkensp** [comment]
This issue was moved to dolkensp/HoloXPLOR#1
