### ISSUE TITLE
Upgrade [or others?] with ' - ' in their name don't parse correctly

### ISSUE THREAD

**Issue by paulpv** [dolkensp/HangarXPLOR#23]
Upgrades that have a ' - ' in their ship name don't parse correctly:
Examples:
"SHIP UPGRADES - CYCLONE TO TUMBRIL - NOVA TANK UPGRADE"
"SHIP UPGRADES - ORIGIN X1 - VELOCITY TO ORIGIN X1 - FORCE UPGRADE"
"SHIP UPGRADES - ORIGIN X1 TO ORIGIN X1 - FORCE UPGRADE"

The problem is a combination of `var titleParts = pledgeName.split(/\s-\s/)` and how `titleParts[index > 0]` are used.

I'm working on a fix for this, but if you have a quick fix idea feel free to impl it yourself.

**Comment by paulpv** [comment]
First pass at fix:
https://github.com/paulpv/HangarXPLOR/commit/8704508fa2533f6620e157aed5a9f2645910cb35

**Comment by paulpv** [comment]
It's a bit buggy; don't take the code yet.

**Comment by dolkensp** [comment]
What are you seeing with the Nova?

![image](https://user-images.githubusercontent.com/469666/42196615-d7c86660-7e76-11e8-95c8-e5304b7e052e.png)

Looks ok to me? I don't have an upgraded X1 to test with tonight...

**Comment by paulpv** [comment]
Improved w/ https://github.com/paulpv/HangarXPLOR/commit/d5aa0323311777962af23c650164c05ac3a41e24

In general the whole `var titleParts = pledgeName.split(/\s-\s/)` seems fragile, but I haven't bothered to come up w/ anything better so I'm sticking to that until I do.

**Comment by paulpv** [comment]
Perhaps it isn't with "Ships", but "Upgrades".
It happened with:
`SHIP UPGRADES - CYCLONE TO TUMBRIL - NOVA TANK UPGRADE`
  came out as `UPGRADE - CYCLONE TO TUMBRIL`
`SHIP UPGRADES - ORIGIN X1 - VELOCITY TO ORIGIN X1 - FORCE UPGRADE`
  came out as `UPGRADE - ORIGIN X1 TO ORIGIN X1`
`SHIP UPGRADES - ORIGIN X1 TO ORIGIN X1 - FORCE UPGRADE`
  came out as `UPGRADE - ORIGIN X1 TO ORIGIN X1`

**Comment by dolkensp** [comment]
Ah yes, I think I noticed something about that a while back and forgot about it (don't often check CCUs)

Excellent. Will take a look next chance I get.

And yes, the whole thing is rather fragile - that's why there's a big "correction" section in the Processing file that attempts to standardize CIGs naming to some extent. The splits and regexes only cover 90% of scenarios - the other 10% we have to fix manually :'(

**Comment by peter-dolkens** [comment]
I suspect this will be resolved in v2 that was just released @paulpv - it's quite a refactor though, but it's designed to standardize the ship codes / manufacturer codes to match up with docs.starcitizen.fans so Erkul and FleetViewer can share/import the data HangarXPLOR exports
