### ISSUE TITLE
Zero dollar melt

### ISSUE THREAD

**Issue by Petosiris** [dolkensp/HangarXPLOR#31]
Some ship items in the hangar has zero value if melted, but the Exchange button is operative anyway. I'd expect the button was greyed out when it was no use to melt. Se attached image.

![hangar_xplor_zero_exchange](https://user-images.githubusercontent.com/40414502/48384022-c4999200-e6e8-11e8-9dda-941f8e5fd7f1.jpg)

**Comment by dolkensp** [comment]
This is intended, not a bug - otherwise you could never clean all those $0 CCUs out of your hangar!
