### ISSUE TITLE
feature quest: show melt amount total for current selection below "total spent"

### ISSUE THREAD

**Issue by Belatar** [dolkensp/HangarXPLOR#33]
hiho,

when looking to melt multiple individual purchases to maybe shoot for a bigger packages, showing the "total melt amount" for the current selection would be helpful.
bonus: have an checkbox ("include in melt total") per hangar list entry to include / exclude invidual list entries.

just an idea :) cheers, bela

**Comment by dolkensp** [comment]
The plugin actually does this already if in understanding this correctly?

Peter Dolkens

**Comment by Belatar** [comment]
hmm, when there are multiple meltable items selected it shows you the sum of those melt values? and there is an option to select / deselect individual entries from the list to be added / ignored to the sum of selected meltable items?
didnt see it, need to check again. will have to wait until friday though as im on a trip rn.

**Comment by dolkensp** [comment]
![image](https://user-images.githubusercontent.com/469666/49096980-b197cd80-f263-11e8-83ed-232ab2ccbf93.png)

I think this is what you're talking about - the Armada + Exploration Packs are worth $3,395 together, as indicated in the top left, above the hangar total.

I've selected these packages simply by clicking on them so they highlight.

Let me know if I've misunderstood you.

**Comment by Belatar** [comment]
thats precisely what i meant, i just didnt try clicking on the packages. thanks :)
