### ISSUE TITLE
Feature Request: Change name label to ship name, if it exists

### ISSUE THREAD

**Issue by Petosiris** [dolkensp/HangarXPLOR#36]
A picture says more than enough so see the attached image.

![Leifr-Eiriksson](https://user-images.githubusercontent.com/40414502/54821444-76059100-4ca2-11e9-9b02-bb59cdee9c4d.jpg)

**Comment by dolkensp** [comment]
I like this one - will review when I get time

**Comment by triesmon** [comment]
@peter-dolkens now that name exists for many more ships it might be nice if the plugin exports this information.

**Comment by peter-dolkens** [comment]
> @peter-dolkens now that name exists for many more ships it might be nice if the plugin exports this information.

That should be quite doable.

The naming one was a bit more complex due to some ships being in combo-packs. Still haven't written it off just yet though.

**Comment by triesmon** [comment]
Though rather than changing the "name" field would be good to add "nickname" or "name_label."

**Comment by Petosiris** [comment]
This request is done now, although in a slightly different way (see attached image) so the issue can be closed.

![hangar-xplor-namable](https://user-images.githubusercontent.com/40414502/111327494-b9b2eb80-866d-11eb-9f1b-c71d3bdfb2b8.jpg)
