### ISSUE TITLE
New "Customize the 300 Series" option breaks Total Spent

### ISSUE THREAD

**Issue by wowiejr** [dolkensp/HangarXPLOR#37]
Hey! Love this idea and it has worked great. 

So with the new Customize your 300 series option on RSI now, purchasing a customization for your 300 series ship, even a free one, breaks the total spent amount of the floating widget. Shows a NaN.
![2019-06-06_1123_-_SC](https://user-images.githubusercontent.com/51070032/59056703-a7c3d800-884d-11e9-9557-bc942cc5d7c9.png)

Just a heads up. Thanks!

**Comment by dolkensp** [comment]
Thanks, will try get on this over the next few hours/days

Should have something by the weekend worst case
