### ISSUE TITLE
Customization button has an issue

### ISSUE THREAD

**Issue by Petosiris** [dolkensp/HangarXPLOR#40]
I've tried the Customization button for the Origin 300 series in Hangar Xplor 3.3.40 and noticed that when pressing it, right after I load the hangar contents, it only brings me back to the hangar. The expected function is to send me to the customization page, of course.

Now, I've also noticed that if I disable Hangar Xplor in my hangar, then reload the hangar content in the RSI view, and press the same Customize button, it brings me to the customization page.

The interesting thing is that when coming back to my Hangar, and re-enable Hangar Xplor, THEN the Customize button(s) work as expected! So I think there might be a flag that's uninitialized or something and only set correct after the customization page is loaded?

**Comment by peter-dolkens** [comment]
Did you ever replicate this?

I haven't managed to. I just tried again and successfully upgraded my 315p too.

If not, I might close it, as it's been a while since it was last seen.

**Comment by Petosiris** [comment]
No, I haven't tried this again since the Origin 300 series came with Customization options.  It may've been Turbulent who messed up this feature in the beginning (it wouldn't be the first time) and then fixed it, I don't know.  We'll have to see if it's repeated when CIG release more ships for Customization, I think.  So go ahead and close this issue now and I can reopen it if happens again later.
