### ISSUE TITLE
Addon not loading

### ISSUE THREAD

**Issue by Rovaxx** [dolkensp/HangarXPLOR#42]
This is probably RSI side but the add-on doesn't do anything other than have the box on the side say Loading Please Wait. The add-on worked flawlessly until the introduction of the 300I customization. Ive spoken to several large fleet owners 200+ ships with the same results. Ive tried Firefox and Chrome browsers with no luck. Without the add-on though just loading the hangar seems very sluggish.

**Comment by dolkensp** [comment]
Unfortunately it's a performance issue on RSIs side.

I'd hoped that they'd resolve the issues after the 300i launch, but it doesn't seem they have.

I'm still trying to work out a solution for people with large hangars.

**Comment by dolkensp** [comment]
Whilst it's still quite slow, this may be resolved with the latest builds.

I'm still trying to implement a safe caching solution which will allow faster plugin initialization, but that's a tricky thing to do safely.

**Comment by Petosiris** [comment]
I tried the latest release just now, v 3.3.59, and it takes longer time now than before v3.3.46 - ca. 4 and 2.5 minutes, respectively. The hangar has 548 items (54 pages with 10 items each, plus page 55 with 3 items).

As Rovaxx says, it worked better before the customization of the 300-series arrived. I don't remember exactly how long I waited then, but I think it was ca. 30 seconds or so. At least not a whole minute.

**Comment by dolkensp** [comment]
Performance is unfortunately CIG related, not related to the extension. It drastically decreased with customisation.

I'm hoping to think of some ways to speed things up by remembering what you loaded previously, but it's tricky to do it accurately.

Peter Dolkens

**Comment by Petosiris** [comment]
I just timed the initial loading of the hangar now, in v3.3.59, and it's 8:35 ... eight minutes and 35 seconds(!) I'm not sure why it takes so long now, compared to five days ago, when it was about half the time, but it'd be very nice if you could do something about this.

**Comment by dolkensp** [comment]
The reason it's gone up even more recently (about 5 days ago) is that CIG put a limit of 10 pledges per page (previously we were loading 100) so we now need to load 10x as many pages to get all the data back.

I think I've figured out a way to quickly and accurately check if your hangar has changed now. Now I just need to check if I can cache the old data without breaking things.

**Comment by peter-dolkens** [comment]
I believe this was resolved with the addition of hangar-cache
