### ISSUE TITLE
RSI Hangar UI has [slightly?] changed and broken plugin

### ISSUE THREAD

**Issue by paulpv** [dolkensp/HangarXPLOR#43]
This is mostly just a heads up; Close if you don't see any issue.
I have been using this [excellent] plugin for well over a year with no problems.
Today I noticed that the pagination of the RSI Hangar appears to have changed and this plugin no longer appears to load the ships correctly.
I don't know yet what else has changed in the Hangar UI, what else might be broken.
I don't know when this change happened, but I did not notice it *not* working yesterday (the last time I used the plugin).

**Comment by paulpv** [comment]
Debugging the code while it is loading the first obvious problem is that the RSI site no longer recognizes the "pagesize" URL parameter:

https://robertsspaceindustries.com/account/pledges?page=1&pagesize=100

That only returns a page of 10 items.

I guess `HangarXPLOR.ProcessPage` would have be changed to loop until the list returns less than 10 items (worst case being the last page has 10 items and the next page is requested that returns 0 items).

**Comment by paulpv** [comment]
A quick test shows that things start working again after changing:
`if ($items.length < 100)`
to
`if ($items.length < 10)`
in `HangarXPLOR.ProcessPage`.

**Comment by dolkensp** [comment]
Thanks for debugging this - I'm busy cramming stuff in a suitcase for a
flight to India tomorrow, but I'll try get a release out before I fly,
otherwise I'll sort it out once I land.

Thanks

**Comment by dolkensp** [comment]
Got a build in the store - hopefully it passes review soon.

Thanks for the report.

**Comment by paulpv** [comment]
I presume you may close this
