### ISSUE TITLE
Can not download JSON

### ISSUE THREAD

**Issue by q220** [dolkensp/HangarXPLOR#46]
When clicking the JSON download button nothing happens.
Looking at the web console, I receive a 

TypeError: pledge.name is undefinedHangarXPLOR.Download.js:40:7

**Comment by q220** [comment]
Confirming that downloading the older Version 3.3.40 works.

Version 3.3.46 (latest) does not work when trying to download the shiplist.json and it also has the NaN value bug.

**Comment by dolkensp** [comment]
Thanks I’m just travelling in India but will be back shortly after citizencon.

If I get a chance at the airport I’ll fix it before citizencon, but if not, I’ll take after.

Thanks for the report

Peter Dolkens

**Comment by dolkensp** [comment]
NaN bug is resolved, which should fix the other issues you mentioned too.

Can you please retry with the latest version and confirm?

**Comment by q220** [comment]
Can confirm that the Hangar total is now being calculated, and the function to download a json file works too!
