### ISSUE TITLE
addon not loading due to settings file

### ISSUE THREAD

**Issue by moozaad** [dolkensp/HangarXPLOR#52]
I get an invisible icon (blank space) on my toolbar that when clicks shows this error...

```
File not found

Firefox can't find the file at moz-extension://568e9a6e-da50-44cc-8e1c-08fb3f7d73e5/ui_resources/HangarXPLOR.Settings.html.


[Try Again]
```

It was working a day or so ago fine.

**Comment by Alter-Eko** [comment]
i am also experiencing this issue on Firefox

**Comment by moozaad** [comment]
Forgot to mention. W10 Firefox 70.0.1

**Comment by gauria** [comment]
Me too
A very similar message

**Comment by dolkensp** [comment]
Looks like the upload went bad - I'll re-upload the package and try again.

**Comment by dolkensp** [comment]
Have re-uploaded the package - version 3.3.65 should resolve the issue

Please let me know if you still experience this after upgrading to version 3.3.65

**Comment by Alter-Eko** [comment]
It fixed it for me

**Comment by moozaad** [comment]
Yep, all good thanks!

**Comment by gauria** [comment]
Perfect! Thx!
