### ISSUE TITLE
CIG "Special" game package not showing with extension

### ISSUE THREAD

**Issue by Fr33L4nc3r** [dolkensp/HangarXPLOR#64]
Hello,

I noticed lately after getting a new game package in my hangar, that it is not shown at all in the list (with all filters cleared)
It also does not show with LTI or Game Package filters.
Here's how it look without the extension:
![image](https://user-images.githubusercontent.com/4953595/87857935-df46f400-c92a-11ea-8c8f-c24f60237d2d.png)
Does it have anything to do with the status "Fulfilled" which differs from standard "Attributed" ?

> <div class="row  trans-03s trans-background executed active">
    <div class="basic-infos clearfix">
        <div class="item-image-wrapper content-block3 executed">
            <div class="image"
                style="background-image:url('/media/smfwnj15y4gq5r/heap_infobox/MISC-Mining-Vehicle-PIECE-2-V19.jpg');">
            </div>
            <div class="corner corner-top-left"></div>
            <div class="corner corner-top-right"></div>
            <div class="corner corner-bottom-left"></div>
            <div class="corner corner-bottom-right"></div>
        </div>
        <div class="wrapper-col">
            <a class="arrow js-expand-arrow trans-02s"><span class="effect trans-02s trans-opacity"></span></a>
            <div class="title-col">
                <h3 class="">
                    MISC Prospector LTI
                </h3>
                <script class="js-pledge-name-reservations" type="application/json">[]</script>
                <script class="js-pledge-nameable-ships" type="application/json">null</script>
                <input type="hidden" class="js-pledge-id" value="22773206">
                <input type="hidden" class="js-pledge-name" value="MISC Prospector LTI">
                <input type="hidden" class="js-pledge-value" value="$0.00 USD">
                <input type="hidden" class="js-pledge-configuration-value" value="$0.00 USD">
                <input type="hidden" class="js-pledge-currency" value="TyCustomer_ledger_-en">
                <input type="hidden" class="js-pledge-last-alpha" value="0">
                <span class="availability executed ">Fulfilled</span>
            </div>
            <div class="date-col">
                <label>Created:</label>
                July 10, 2020
            </div>
            <div class="items-col">
                <label>Contains:</label>
                Prospector and 3 items
            </div>
        </div>
    </div>
    <div class="items more js-more trans-02s trans-height">
        <h2>Items</h2>
        <span class="clear"></span>
        <div class="content-block1">
            <div class="with-images">
                <div class="item ">
                    <div class="image"
                        style="background-image:url('/media/smfwnj15y4gq5r/subscribers_vault_thumbnail/MISC-Mining-Vehicle-PIECE-2-V19.jpg');">
                    </div>
                    <div class="text">
                        <div class="title">Prospector</div>
                        <div class="kind">Ship</div>
                        <div class="liner">Musashi Industrial &amp; Starflight Concern (<span>MISC</span>)</div>
                    </div>
                </div>
                <div class="item ">
                    <div class="image"
                        style="background-image:url('/media/v3awjmunb39e1r/subscribers_vault_thumbnail/AeroView_02.jpg');">
                    </div>
                    <div class="text">
                        <div class="title">Aeroview Hangar</div>
                        <div class="kind">Hangar level</div>
                    </div>
                </div>
                <div class="cboth"></div>
            </div>
            <div class="also-contains">Also Contains</div>
            <div class="without-images">
                <div class="item ">
                    <div class="title">
                        Lifetime Insurance
                    </div>
                </div>
                <div class="item ">
                    <div class="title">
                        Star Citizen Digital Download
                    </div>
                </div>
                <div class="cboth"></div>
            </div>
            <div class="top-line-thin"></div>
            <div class="top-line"></div>
            <div class="corner corner-top-left"></div>
            <div class="corner corner-top-right"></div>
            <div class="corner corner-bottom-left"></div>
            <div class="corner corner-bottom-right"></div>
        </div>
    </div>
    <div class="line">
        <div class="effect trans-02s trans-opacity"></div>
    </div>
</div>

Let me know if any other details is required.
Thanks again for providing such a great extension that overall the hangar so much !

**Comment by peter-dolkens** [comment]
This is an excellent bug report, has everything I need to fix it I believe

I’ll take a look when I can.

Thanks

Peter Dolkens

**Comment by PolecatEZ** [comment]
I'm having the exact same issue with the following package:

PACKAGE - AMD NEVER SETTLE SPACE EDITION

If the XPLORer plugin is active, the package and ship are entirely invisible on my list.  When I turn it off, the package appears as normal.

**Comment by Fr33L4nc3r** [comment]
The issue I posted initially is fixed by the current version as I'm concerned, hence closing this issue 👍 
![image](https://user-images.githubusercontent.com/4953595/103405998-64306d80-4b59-11eb-948f-ab3ffcc14b18.png)
