### ISSUE TITLE
Caching Stale Data

### ISSUE THREAD

**Issue by Darkstar77** [dolkensp/HangarXPLOR#68]
Google Chrome, latest version. Linux.

I've been using Hangar Xplor pretty much since it came out, and I love it. Recently I've noticed a strange behavior. I have multiple computers. Computer A, and Computer B in this example. 

I've loaded my hangar on both A & B. On Computer A, I make some changes, apply a CCU, melt a ship, etc.. It is reflected on Computer A without issue. I log in on Computer B, and Computer B shows me stale data, how my hangar was before I changed anything; the same as it was the previous time I loaded it. 

Initially, I could resolve this by logging out, and logging back in. That is no longer working. I disable the extension on Computer B, and the data is all there and correct in the default (yuk) hangar view. I reenable the extension, and bam, stale data again. A forced refresh does not solve this either (CTRL+F5). Clearing my browser data (cookies and cached data) does not seem to fix this.

It would be useful if there was a simple way to force the extension to load fresh data.

**Comment by peter-dolkens** [comment]
Thanks for the detailed report darkstar - it seems Chrome is having some difficulty syncing the cache between machines.

This is meant to be handled automatically by Chrome, but I should be able to add some extra protections in place to detect if it has failed.

I also wanted to add a clear cache button, so will see what I can do this week.

Thanks for the report

**Comment by Krunch** [comment]
I looked at the code and you seem to be using `chrome.storage.local` instead of `chrome.storage.sync`. I don't believe local is synchronized between browsers.

**Comment by peter-dolkens** [comment]
Thanks for the pointer Stefan.

My rig has actually been offline most of last week - finally online again
as of last night, just in time for me to return to work :(

I know I was using different parts to cache/sync different things due to
storage constraints, so I'll take a closer look, maybe I got the two
crossed.

**Comment by Da-Geek** [comment]
Just to add another voice to this issue, I am also having the same issue on Multiple Machines,
Fedora, Pixelbook/ChromeOS and Windows.

Amazing work with the AddOn! Keep it up :-)
