### ISSUE TITLE
CIG says HangarXPLOR is not be compatible with naming ships

### ISSUE THREAD

**Issue by Petosiris** [dolkensp/HangarXPLOR#76]
You've probably already heard about this, but I create a new issue for it here so it's duly recorded in the project.

The naming feature CIG have made available is said to cause problems if the HangarXPLOR extention is enabled when you try to name a ship.  See https://support.robertsspaceindustries.com/hc/en-us/articles/360019839074 for more info, and the excerpt screenshot I've attached below.

NOTE: I use version **3.3.65** of HangarXPLOR (for Opera) at the moment and that version don't have any issues when naming ships, as far as I can see.  I've named several ships the recent days when HangarXPLOR is running and enabled, and with no problems.  But a friend of mine, who runs version **3.3.106** said to me he had this issue and therefore had to disable the extention before naming his ships.  

This may be a clue to something that changed between these two versions and affected the naming feature.

Obviously, disabling the HangarXPLOR extention is a real pain when you then have to browse through, maybe, hundreds of pledges, 10 at a time, to find the ship you're interested in naming.  That's why we need this issue fixed ASAP.   :)

![Ship-Naming-HangarXPLOR](https://user-images.githubusercontent.com/40414502/110665561-c8f6ec80-81c8-11eb-8c94-21a342a47955.jpg)

**Comment by peter-dolkens** [comment]
Thanks - I had no idea there was a problem.

I believe hangar caching may be interfering with this new feature being enabled without any changes to your actual hangar log.

Investigating a way to fix.
