### ISSUE TITLE
Extension broken on Firefox v89.0b15 (64 bits)

### ISSUE THREAD

**Issue by sonicsilhouette** [dolkensp/HangarXPLOR#84]
Reinstalled the extension today and found it completely broken (no icon in the upper toolbar).

I use a portable installation of Firefox v89.0b15 (64 bits).

![image](https://user-images.githubusercontent.com/65699547/119260961-6ad98300-bbd5-11eb-96f8-df84f64a9ded.png)

Basically it says:

"Firefox cannot find the file at the following adresse moz-extension://db33583e-55bc-4289-a3d6-3244ed6b7947/ui_resources/HangarXPLOR.Settings.html"

Let me know if you require more data.

**Comment by peter-dolkens** [comment]
Thanks, re-uploading now - it looks like something got corrupted during
the upload last night.

>

**Comment by sonicsilhouette** [comment]
It's working again, thanks Peter.
