### ISSUE TITLE
extention broken 

### ISSUE THREAD

**Issue by TDPMojo** [dolkensp/HangarXPLOR#85]
it cannot find file
![Cant use Xplor](https://user-images.githubusercontent.com/84671464/119263520-5e413480-bbad-11eb-9d4f-e96e8896de7c.png)

**Comment by peter-dolkens** [comment]
Thanks, re-uploading now - it looks like something got corrupted during the
upload last night.

>

**Comment by TDPMojo** [comment]
awesome news, thanks
