### ISSUE TITLE
ship picture

### ISSUE THREAD

**Issue by TDPMojo** [dolkensp/HangarXPLOR#86]
I am not sure this is an extension issue or rsi website, but the ship pic of the Scorpius is not what it should be 

![Screenshot_2021-05-23 My Hangar - Roberts Space Industries Follow the development of Star Citizen and Squadron 42(1)](https://user-images.githubusercontent.com/84671464/119265440-bd567780-bbb4-11eb-8078-2297acd80e3a.png)

**Comment by peter-dolkens** [comment]
Interesting - I'll take a look

**Comment by Tatstahanno** [comment]
Same for the Gatac Railen.
![Screenshot 2022-01-08 211007](https://user-images.githubusercontent.com/13168098/148660085-fbb09add-7d62-4a88-b070-54dd08205f6b.png)

**Comment by peter-dolkens** [comment]
These should both be caught by the v2 rewrite that just went live

Let me know if you're still having issues

Sorry for the delay!
