### ISSUE TITLE
Are there any known parsers of the Hangar Transfer Format?

### ISSUE THREAD

**Issue by TheAnachronism** [dolkensp/HangarXPLOR#87]
I'm thinking about developing a service which at some point could load a downloaded json file for all the ship information.
Rather then writing the entire json parser (wouldn't be much but still), I was thinking if there were any existing libraries which already process such a json file.
If not I'd be willing to write a library in C# for that purpose.

**Comment by peter-dolkens** [comment]
Hi @TheAnachronism - see docs.starcitizen.fans

The core data format is based around `ship-codes.json` - the v2 rewrite was just released which should ensure most(all?) ships are exporting in this format now.

Let me know if there's any other questions
