### ISSUE TITLE
Drake Corsair CCU replacement picture not showing

### ISSUE THREAD

**Issue by zsdonny** [dolkensp/HangarXPLOR#90]
I believe it is a feature for HangarXPLOR to replace the picture of final CCU result? It is not showing for my CCU'd Drake Corsair

![image](https://user-images.githubusercontent.com/15925621/133916190-cd941e77-6016-4248-bc90-64836c0adcee.png)

It works fine for the Cutlass Red

![image](https://user-images.githubusercontent.com/15925621/133916238-f256eda6-8e1e-4c2f-aabf-aee2fadaa361.png)

**Comment by peter-dolkens** [comment]
Thanks I'll take a look at this tonight

Peter Dolkens

**Comment by zsdonny** [comment]
Hello Peter! I noted from `HangarXPLOR.Ships.js`, it seems that the replacement thumbnail is manually mapped (please correct me if I am wrong I am not very versed in js) using official website medias on `robertspaceindustries.com` and that there isn't an entry for the Drake Corsair

I asked a friend that has the Drake Corsair as a base pledge in their hangar and extracted the media URL. Hope it helps with the issue!

`https://media.robertsspaceindustries.com/2xatcl9uglt91/heap_infobox.jpg`

![image](https://user-images.githubusercontent.com/15925621/134107900-8dcb6934-95a7-4b96-ad88-d3b9bfc9c2f9.png)

**Comment by zsdonny** [comment]
Hello Peter,

Have you found out anything with this behavior for the browser add-on? Thanks!

**Comment by zsdonny** [comment]
Hey Peter,

Do you know if that's why it occur? Thanks!

**Comment by zsdonny** [comment]
I haven't done this before and gave loading the extension locally a go, I added said media resource URL to `HangarXPLOR.Ships.js` and it seems to work pretty well

![image](https://user-images.githubusercontent.com/15925621/144391634-b770833e-8586-4982-b6bc-3207c83ea4c0.png)

#91 Tested with Firefox 94.0.2, I hope this get updated in the browser add-on store releases soon!
