### ISSUE TITLE
Your hangar is empty

### ISSUE THREAD

**Issue by PopeKael** [dolkensp/HangarXPLOR#92]
I just took a look in my hangar and when the extension is active, it tells me "Your hangar is empty"

When I disable the extension, I can see all my gear. Is there something broken in the extension?

Oh, it was working when I installed the extension and I successfully exported the file so this seems to be something recent.

**Comment by zsdonny** [comment]
![image](https://user-images.githubusercontent.com/15925621/146136155-01aaa00e-9ca1-4ff0-9454-91c2d7ac2773.png)

are you sure it is not filtered to something you don't have?

does this issue persist if you disable all other browser extension other than HangarXPLOR?

**Comment by peter-dolkens** [comment]
Hi @PopeKael, sorry I missed this.

Have you bought anything new, or "purchased" any of the christmas gifts?

**Comment by PopeKael** [comment]
Ok, that was my blunder. It seems like the dropdown selection remembers the last filter you had open. Once I reset it to ships, it all worked as expected again. Not sure how I missed that! Thanks

**Comment by peter-dolkens** [comment]
Not a problem - enjoy!
