### ISSUE TITLE
Wrong thumbnail for the Kraken Privateer

### ISSUE THREAD

**Issue by EricB1978** [dolkensp/HangarXPLOR#93]
![image](https://user-images.githubusercontent.com/86251895/170479445-4be3a379-7527-4119-8544-d108c2156624.png)

This is the thumbnail for the Kraken Privateer

**Comment by zsdonny** [comment]
Do you have the image URL to it, right now the pluigin setup seems to be linking to RSI media URL directly

**Comment by EricB1978** [comment]
https://media.robertsspaceindustries.com/6lus62r58mlfr/heap_infobox.jpg

or in my imgur

https://i.imgur.com/DNePrnm.png

**Comment by peter-dolkens** [comment]
Sorry about the delay - this should be picked up in the latest version that was just published. Please let me know if there's any issues

**Comment by EricB1978** [comment]
All the vignettes (at least the ships I have) look right to me now. Nice work.

________________________________
De : Peter Dolkens ***@***.***>
Envoyé : mercredi 2 novembre 2022 02:05
À : dolkensp/HangarXPLOR ***@***.***>
Cc : Eric ***@***.***>; Author ***@***.***>
Objet : Re: [dolkensp/HangarXPLOR] Wrong thumbnail for the Kraken Privateer (Issue #93)


Sorry about the delay - this should be picked up in the latest version that was just published. Please let me know if there's any issues
