### ISSUE TITLE
Is there a better system to update hangar image replacement than manually curating a list?

### ISSUE THREAD

**Issue by zsdonny** [dolkensp/HangarXPLOR#94]
Right now my hangar has a lot of out of date images especially for newer ships... so far my understanding of how the plugin work is that the replacement mapping is curated by `HangarXPLOR.Ships.js ` manually using media URL hosted on RSI.com ... This seems difficult to maintain since there doesn't seem to be a way to reliable scrape/fetch the hangar thumbnail media URL unless you have a listing in your hangar.

Is there a better way to do this? I don't mind maintaining the `HangarXPLOR.Ships.js ` list manually if anyone can suggest a way to get the hangar thumbnail URL from RSI.com

**Comment by peter-dolkens** [comment]
Hi @zsdonny  -  things got a bit hectic in real life so I hadn't pulled the trigger on the release of my next major update - it had been sitting on a branch for ages 😞 

I've just released it to Firefox + Chrome stores, so you should start seeing the updated images and features shortly.

The new version is built around a ship-codes.json, with the intention being that a few different fan projects could share/standardize on the codes used over at docs.starcitizen.fans

Give it a go, and let me know how you go
