### ISSUE TITLE
Wrong thumbnail for upgraded Gatac Railen

### ISSUE THREAD

**Issue by Tatstahanno** [dolkensp/HangarXPLOR#97]
![148660085-fbb09add-7d62-4a88-b070-54dd08205f6b](https://user-images.githubusercontent.com/13168098/194390236-0e39254f-bc40-4115-b71f-c5164689c0f8.png)

**Comment by peter-dolkens** [comment]
Should be resolved - can you please confirm

**Comment by Tatstahanno** [comment]
Just checked and it's fixed on Chrome.
Thanks.

I'm guessing the update hasn't been rolled to the Firfox extension yet?

**Comment by peter-dolkens** [comment]
Firefox has been rolled out too - though they sometimes take a bit longer to appear and update.Peter DolkensOn 2 Nov 2022, at 08:13, Tatstahanno ***@***.***> wrote:﻿
Just checked and it's fixed on Chrome.
Thanks.
I'm guessing the update hasn't been rolled to the Firfox extension yet?
